#!/usr/bin/env bash

# set -eux -o pipefail

# the 1st argument of this script expects the runnable
if [ "${1}" = "" ]
then
  echo "Usage: $0 <jmeter>"
  exit
fi

export TARGET="${1}"

./scripts/docker_build_${TARGET} "${@:2}"
